### ISSUE TITLE
VS 2022可以编译吗？ 

### ISSUE THREAD

**Issue by yiting888** [fbmly007/NesX#1]

**Comment by fbmly007** [comment]
现在CPU里用的switch case的使用方式(case 1 ... 10) 在VS上不支持, 这块需要改成函数指针的形式, 我这2天改一下看看

**Comment by fbmly007** [comment]
现在CPU里用的switch case的使用方式(case 1 ... 10) 在VS上不支持, 这块需要改成函数指针数组的形式, 我这2天改一下看看

**Comment by fbmly007** [comment]
分支 `main_vs` 已经在代码上对VS编译器进行了修改, 可以编译和运行, 不过还没有进行优化, 如果需要Debug调试 可以参考`已知问题`
